# Generated by Django 3.1.7 on 2021-03-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210303_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
